@api = http://localhost:4000/products

GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "id": 2,
    "name": "Zapatilla2",
    "productType": "Running shoes",
    "price": 50,
    "rating": 4,
    "image": "https://s2.r29static.com/bin/entry/ebd/0,675,2000,1050/x,80/1929471/image.jpg",
    "description": "Zapatillas deportivas diseñadas para el Running."
}
###
GET http://localhost:4000/products/1